import React from 'react'
import {
    Route,
    BrowserRouter as Router,
    Switch
} from 'react-router-dom'
import {
    ChannelNew,
    Channels,
    ChannelUpdate,
    ForgotPassword,
    Home,
    Login,
    NotFound,
    PasswordReset,
    BranchNew,
    Branches,
    BranchUpdate,
    Register,
    FaqNew,
    Faqs,
    FaqUpdate,
    PromotionsNew,
    Promotions,
    PromotionsUpdate,
    UserNew,
    Users,
    UserUpdate,
    FeaturedContentNew,
    FeaturedContents,
    FeaturedContentUpdate,
    Contents,
    ContentNew,
    ContentUpdate,
    FaqCategoryUpdate,
    FaqCategoryNew,
    FaqCategories,
    Covers,
    CoverNew,
    CoverUpdate,
    ContentCategories,
    ContentCategoryNew,
    ContentCategoryUpdate,
    Features,
    FeatureNew,
    FeatureUpdate,
    Plans,
    PlanNew,
    PlanUpdate,
    ChannelCategories,
    ChannelCategoryNew,
    ChannelCategoryUpdate,
    Values,
    ValueNew,
    ValueUpdate
} from './pages'
import {
    AboutSetting,
    HomeSetting,
    ReplaySetting,
    ChannelSetting,
    ContactSetting,
    CoverSetting,
} from './forms';

export default () => (
    <Router>
        <Switch>
            <Route
                path="/signin"
                component={Login}
            />
            <Route
                path="/signup"
                component={Register}
            />
            <Route
                path="/forgot/password"
                component={ForgotPassword}
            />
            <Route
                path="/password/reset/:token"
                component={PasswordReset}
            />
            <Route
                path="/"
                component={Home}
                exact
            />
            <Route
                path="/users/new"
                component={UserNew}
            />
            <Route
                path="/users/:id"
                component={UserUpdate}
            />
            <Route
                path="/users"
                component={Users}
            />
            <Route
                path="/featured/contents/new"
                component={FeaturedContentNew}
            />
            <Route
                path="/featured/contents/:id"
                component={FeaturedContentUpdate}
            />
            <Route
                path="/featured/contents"
                component={FeaturedContents}
            />
            <Route
                path="/content/categories/new"
                component={ContentCategoryNew}
            />
            <Route
                path="/content/categories/:id"
                component={ContentCategoryUpdate}
            />
            <Route
                path="/content/categories"
                component={ContentCategories}
            />
            <Route
                path="/branches/new"
                component={BranchNew}
            />
            <Route
                path="/branches/:id"
                component={BranchUpdate}
            />
            <Route
                path="/branches"
                component={Branches}
            />
            <Route
                path="/faqs/new"
                component={FaqNew}
            />
            <Route
                path="/faqs/:id"
                component={FaqUpdate}
            />
            <Route
                path="/faqs"
                component={Faqs}
            />
            <Route
                path="/channels/new"
                component={ChannelNew}
            />
            <Route
                path="/channels/:id"
                component={ChannelUpdate}
            />
            <Route
                path="/channels"
                component={Channels}
            />
            <Route
                path="/promotions/new"
                component={PromotionsNew}
            />
            <Route
                path="/promotions/:id"
                component={PromotionsUpdate}
            />
            <Route
                path="/promotions"
                component={Promotions}
            />
            <Route
                path="/contents/new"
                component={ContentNew}
            />
            <Route
                path="/contents/:id"
                component={ContentUpdate}
            />
            <Route
                path="/contents"
                component={Contents}
            />
            <Route
                path="/faq_categories/new"
                component={FaqCategoryNew}
            />
            <Route
                path="/faq_categories/:id"
                component={FaqCategoryUpdate}
            />
            <Route
                path="/faq_categories"
                component={FaqCategories}
            />
            <Route
                path="/covers/new"
                component={CoverNew}
            />
            <Route
                path="/covers/:id"
                component={CoverUpdate}
            />
            <Route
                path="/covers"
                component={Covers}
            />
            <Route
                path="/features/new"
                component={FeatureNew}
            />
            <Route
                path="/features/:id"
                component={FeatureUpdate}
            />
            <Route
                path="/features"
                component={Features}
            />
            <Route
                path="/plans/new"
                component={PlanNew}
            />
            <Route
                path="/plans/:id"
                component={PlanUpdate}
            />
            <Route
                path="/plans"
                component={Plans}
            />
            <Route
                path="/values/new"
                component={ValueNew}
            />
            <Route
                path="/values/:id"
                component={ValueUpdate}
            />
            <Route
                path="/values"
                component={Values}
            />
            <Route
                path="/channel/categories/new"
                component={ChannelCategoryNew}
            />
            <Route
                path="/channel/categories/:id"
                component={ChannelCategoryUpdate}
            />
            <Route
                path="/channel/categories"
                component={ChannelCategories}
            />
            <Route
                path="/settings/home"
                component={HomeSetting}
            />
            <Route
                path="/settings/about"
                component={AboutSetting}
            />
            <Route
                path="/settings/replay"
                component={ReplaySetting}
            />
            <Route
                path="/settings/channel"
                component={ChannelSetting}
            />
            <Route
                path="/settings/contact"
                component={ContactSetting}
            />
            <Route
                path="/settings/cover"
                component={CoverSetting}
            />
            <Route component={NotFound} />
        </Switch>
    </Router>
)
