import React from 'react'
import {
    Route,
    BrowserRouter as Router,
    Switch
} from 'react-router-dom'
import {
    ForgotPassword,
    Home,
    Login,
    NotFound,
    PasswordReset,
    Register,
    UserNew,
    Users,
    UserUpdate,
    Works,
    WorksNew,
    WorksUpdate,
    ClientsUpdate,
    ClientsNew,
    Clients,
    TeamUpdate,
    TeamNew,
    Team,
    Filter,
    FilterNew,
    FilterUpdate,
    About,
    AboutUpdate,
    AboutNew
} from './pages'

import{
    HomeSetting,
    AboutSetting,
    ContactSetting,
    PortfolioSetting,
    FooterSetting,
    LogoSetting
} from './forms'

export default () => (
    <Router>
        <Switch>
            <Route
                path="/signin"
                component={Login}
            />
            <Route
                path="/signup"
                component={Register}
            />
            <Route
                path="/forgot/password"
                component={ForgotPassword}
            />
            <Route
                path="/password/reset/:token"
                component={PasswordReset}
            />
            <Route
                path="/"
                component={Home}
                exact
            />
            <Route
                path="/users/new"
                component={UserNew}
            />
            <Route
                path="/users/:id"
                component={UserUpdate}
            />
            <Route
                path="/users"
                component={Users}
            />
            <Route
                path="/works/new"
                component={WorksNew}
            />
            <Route
                path="/works/:id"
                component={WorksUpdate}
            />
            <Route
                path="/works"
                component={Works}
            />
            <Route
                path="/clients/new"
                component={ClientsNew}
            />
            <Route
                path="/clients/:id"
                component={ClientsUpdate}
            />
            <Route
                path="/clients"
                component={Clients}
            />
            <Route
                path="/team/new"
                component={TeamNew}
            />
            <Route
                path="/team/:id"
                component={TeamUpdate}
            />
            <Route
                path="/team"
                component={Team}
            />
            <Route
                path="/filter/new"
                component={FilterNew}
            />
            <Route
                path="/filter/:id"
                component={FilterUpdate}
            />
            <Route
                path="/filter"
                component={Filter}
            />
            <Route
                path="/about/new"
                component={AboutNew}
            />
            <Route
                path="/about/:id"
                component={AboutUpdate}
            />
            <Route
                path="/about"
                component={About}
            />
           <Route
                path="/settings/home"
                component={HomeSetting}
            />
            <Route
                path="/settings/about"
                component={AboutSetting}
            />
            <Route
                path="/settings/contact"
                component={ContactSetting}
            />
            <Route
                path="/settings/portfolio"
                component={PortfolioSetting}
            />
            <Route
                path="/settings/footer"
                component={FooterSetting}
            />
            <Route
                path="/settings/logo"
                component={LogoSetting}
            />
            <Route component={NotFound} />
        </Switch>
    </Router>
)
